spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/recommend?useUnicode=true&characterEncoding=utf-8&useSSL=true
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  thymeleaf:
    cache: false
  application:
      name: recommend-web
  cloud:
      config:
        uri: http://localhost:8888
  zipkin:
      base-url: http://localhost:9411
      sender:
          type: web # 另外2个是 rabbit和kafka

feign:
  hystrix:
    enabled: true

#logging.level.org.springframework.security=info
#spring.thymeleaf.cache=false
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

management:
  endpoints:
    web:
      exposure:
#        include: hystrix.stream
        include: '*'